In [1]:
import pandas as pd
dataset = pd.read_csv("insurance_pre.csv")

In [2]:
dataset.head(5)

   age     sex     bmi  children smoker      charges
0   19  female  27.900         0    yes  16884.92400
1   18    male  33.770         1     no   1725.55230
2   28    male  33.000         3     no   4449.46200
3   33    male  22.705         0     no  21984.47061
4   32    male  28.880         0     no   3866.85520

In [3]:
dataset = pd.get_dummies(dataset, dtype='int', drop_first=True)

In [4]:
dataset.head(5)

   age     bmi  children      charges  sex_male  smoker_yes
0   19  27.900         0  16884.92400         0           1
1   18  33.770         1   1725.55230         1           0
2   28  33.000         3   4449.46200         1           0
3   33  22.705         0  21984.47061         1           0
4   32  28.880         0   3866.85520         1           0

In [5]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [6]:
independent = dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dependent = dataset[['charges']]

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(independent, dependent, test_size=0.3, random_state=0)

In [8]:
from sklearn.svm import SVR
regressor = SVR()

In [9]:
regressor.fit(X_train, y_train)

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR()

In [10]:
y_pred = regressor.predict(X_test)

In [11]:
from sklearn.metrics import r2_score
r_score = r2_score(y_test, y_pred)
r_score

-0.08842732776913875

In [12]:
regressor = SVR(kernel='linear')
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

-0.11166128719608448

In [13]:
regressor = SVR(kernel='poly')
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

-0.06429258402105531

In [14]:
regressor = SVR(kernel='sigmoid')
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

-0.0899412170256757

In [15]:
regressor = SVR(kernel='rbf', gamma='auto')
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

-0.08947360164580087

In [16]:
regressor = SVR(kernel='linear', gamma='auto')
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

-0.11166128719608448

In [17]:
regressor = SVR(kernel='sigmoid', gamma='auto')
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

-0.0897090046144422

In [18]:
regressor = SVR(kernel='rbf', gamma='auto', C=10)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

-0.08749793867433864

In [19]:
regressor = SVR(kernel='linear', gamma='auto', C=10)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

-0.0016176324886472138

In [20]:
regressor = SVR(kernel='sigmoid', gamma='auto', C=10)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

-0.0897090046144422

In [21]:
regressor = SVR(kernel='rbf', gamma='auto', C=100)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

-0.07459036554857645

In [22]:
regressor = SVR(kernel='linear', gamma='auto', C=100)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.5432818196692804

In [23]:
regressor = SVR(kernel='sigmoid', gamma='auto', C=100)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

-0.0897090046144422

In [24]:
regressor = SVR(kernel='linear', gamma='auto', C=1000)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.634036931263208

In [25]:
regressor = SVR(kernel='linear', gamma='auto', C=10000)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.744482485232016

In [26]:
regressor = SVR(kernel='linear', gamma='auto', C=100000)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.7436153490739621

In [27]:
regressor = SVR(kernel='linear', gamma='scale', C=10000)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.744482485232016

In [28]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train=sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [30]:
regressor = SVR(kernel='linear')
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

-0.010102665316081394

In [31]:
regressor = SVR(kernel='rbf')
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

-0.08338238593619329

In [32]:
regressor = SVR(kernel='poly')
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

-0.07569965570860893

In [33]:
regressor = SVR(kernel='sigmoid')
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

-0.07542924281107188

In [34]:
regressor = SVR(kernel='linear', gamma='scale', C=10)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.46246841423396834

In [35]:
regressor = SVR(kernel='linear', gamma='scale', C=100)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.6288792857320369

In [37]:
regressor = SVR(kernel='linear', gamma='scale', C=1000)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.7649311738597411

In [38]:
regressor = SVR(kernel='linear', gamma='scale', C=10000)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.7414230132360546

In [39]:
regressor = SVR(kernel='linear', gamma='scale', C=100000)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.7414188999908664