In [1]:
import pandas as pd
dataset = pd.read_csv("insurance_pre.csv")

In [2]:
dataset.head(5)

   age     sex     bmi  children smoker      charges
0   19  female  27.900         0    yes  16884.92400
1   18    male  33.770         1     no   1725.55230
2   28    male  33.000         3     no   4449.46200
3   33    male  22.705         0     no  21984.47061
4   32    male  28.880         0     no   3866.85520

In [3]:
dataset = pd.get_dummies(dataset, dtype='int', drop_first=True)

In [4]:
dataset.head(5)

   age     bmi  children      charges  sex_male  smoker_yes
0   19  27.900         0  16884.92400         0           1
1   18  33.770         1   1725.55230         1           0
2   28  33.000         3   4449.46200         1           0
3   33  22.705         0  21984.47061         1           0
4   32  28.880         0   3866.85520         1           0

In [5]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [6]:
independent = dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dependent = dataset[['charges']]

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(independent, dependent, test_size=0.3, random_state=0)

In [8]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor()

In [9]:
regressor.fit(X_train, y_train)

DecisionTreeRegressor()

In [10]:
y_pred = regressor.predict(X_test)

In [11]:
from sklearn.metrics import r2_score
r_score = r2_score(y_test, y_pred)
r_score

0.6891794268813551

In [12]:
regressor = DecisionTreeRegressor(criterion='friedman_mse')
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

0.6970466979396949

In [13]:
regressor = DecisionTreeRegressor(criterion='absolute_error')
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

0.6852983225523321

In [14]:
regressor = DecisionTreeRegressor(criterion='poisson')
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

0.7223345541543372

In [15]:
regressor = DecisionTreeRegressor(criterion='squared_error', splitter='random')
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

0.7103760479356425

In [16]:
regressor = DecisionTreeRegressor(criterion='friedman_mse', splitter='random')
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

0.6558654253708285

In [17]:
regressor = DecisionTreeRegressor(criterion='absolute_error', splitter='random')
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

0.7647617607388132

In [18]:
regressor = DecisionTreeRegressor(criterion='poisson', splitter='random')
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

0.6890828681738785

In [19]:
regressor = DecisionTreeRegressor(criterion='squared_error', splitter='best', max_features='sqrt')
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

0.7045470089684492

In [23]:
regressor = DecisionTreeRegressor(criterion='friedman_mse', splitter='best', max_features='sqrt')
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

0.6335639219390758

In [21]:
regressor = DecisionTreeRegressor(criterion='absolute_error', splitter='best', max_features='sqrt')
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

0.7792992886072756

In [22]:
regressor = DecisionTreeRegressor(criterion='poisson', splitter='best', max_features='sqrt')
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

0.687967195709408

In [24]:
regressor = DecisionTreeRegressor(criterion='squared_error', splitter='random', max_features='sqrt')
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

0.5670555298501802

In [26]:
regressor = DecisionTreeRegressor(criterion='friedman_mse', splitter='random', max_features='sqrt')
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

0.6308727130073952

In [27]:
regressor = DecisionTreeRegressor(criterion='absolute_error', splitter='random', max_features='sqrt')
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

0.7043733563696029

In [28]:
regressor = DecisionTreeRegressor(criterion='poisson', splitter='random', max_features='sqrt')
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

0.7129472443923185

In [30]:
regressor = DecisionTreeRegressor(criterion='squared_error', splitter='best', max_features='log2')
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

0.6733921023731033

In [31]:
regressor = DecisionTreeRegressor(criterion='friedman_mse', splitter='best', max_features='log2')
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

0.7460429533036814

In [32]:
regressor = DecisionTreeRegressor(criterion='absolute_error', splitter='best', max_features='log2')
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

0.7367141811637148

In [33]:
regressor = DecisionTreeRegressor(criterion='poisson', splitter='best', max_features='log2')
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

0.687584830565753

In [34]:
regressor = DecisionTreeRegressor(criterion='squared_error', splitter='random', max_features='log2')
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

0.6573010494577158

In [35]:
regressor = DecisionTreeRegressor(criterion='friedman_mse', splitter='random', max_features='log2')
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

0.6505893159873098

In [36]:
regressor = DecisionTreeRegressor(criterion='absolute_error', splitter='random', max_features='log2')
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

0.6761346040750211

In [37]:
regressor = DecisionTreeRegressor(criterion='poisson', splitter='random', max_features='log2')
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
r_score = r2_score(y_test, y_pred)
r_score

0.6098062069516472