In [1]:
import pandas as pd
dataset=pd.read_csv("50_Startups.csv")

In [2]:
dataset.head(5)

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [3]:
# Convert categorical value into numeric value
dataset = pd.get_dummies(dataset, dtype=int, drop_first=True)

In [5]:
dataset.head(5)

,R&D Spend,Administration,Marketing Spend,Profit,State_Florida,State_New York
0,165349.20,136897.80,471784.10,192261.83,0,1
1,162597.70,151377.59,443898.53,191792.06,0,0
2,153441.51,101145.55,407934.54,191050.39,1,0
3,144372.41,118671.85,383199.62,182901.99,0,1
4,142107.34,91391.77,366168.42,166187.94,1,0

In [7]:
dataset.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'Profit',
       'State_Florida', 'State_New York'],
      dtype='object')

In [13]:
independent = dataset[['R&D Spend', 'Administration', 'Marketing Spend','State_Florida', 'State_New York']]
independent.head(5)

   R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
0  165349.20       136897.80        471784.10              0               1
1  162597.70       151377.59        443898.53              0               0
2  153441.51       101145.55        407934.54              1               0
3  144372.41       118671.85        383199.62              0               1
4  142107.34        91391.77        366168.42              1               0

In [15]:
dependent=dataset[['Profit']]
dependent.head(5)

      Profit
0  192261.83
1  191792.06
2  191050.39
3  182901.99
4  166187.94

In [16]:
# importing train_test_split library from sklearn.model_selection library collection
from sklearn.model_selection import train_test_split
# spliting the dataset to train and test with ratio of 70:30 and assign to variable X_train, X_test, y_train and y_test. 
#for industry standard X represents input, y represents output
X_train,X_test,y_train,y_test=train_test_split(independent, dependent,test_size=0.30, random_state=0)

In [17]:
# importing LinearRegression library from sklearn.linear_model library collection
from sklearn.linear_model import LinearRegression
#assign LinearRegression to a regressor variable
regressor = LinearRegression()
# Train the model using fit method and passing both input and output training value 
regressor.fit(X_train,y_train)

LinearRegression()

In [18]:
# coef_ variable contains weight of the Linear regression
weight = regressor.coef_
weight

array([[7.90840255e-01, 3.01968165e-02, 3.10148566e-02, 4.63028992e+02,
        3.04799573e+02]])

In [19]:
# intercept_ variable contains the bias value or starting value or intercept value
bias = regressor.intercept_
bias

array([42403.87087053])

In [20]:
# predict the value passsing test input value
y_pred = regressor.predict(X_test)

In [21]:
# Model evaluation using R2_score. Always output between 0 to 1. If the value is near to 1 then the model good model.
# importing r2_score library from sklearn.metrics collections
from sklearn.metrics import r2_score
# evaluate the model using original test output value  vs predicted test value and assign to variable
r_score = r2_score(y_test, y_pred)

In [22]:
# diplay variable
r_score

0.9358680970046243

In [23]:
# Save the model
# import pickle library
import pickle
# Assign the model filename into a filename variable
filename = "finalized_model_mlr.sav"

In [24]:
# Dump the model / save the model into filename
pickle.dump(regressor,open(filename,'wb'))

In [25]:
#Verifying the saved model. 
#Load the saved model from the saved file
loaded_model = pickle.load(open("finalized_model_mlr.sav",'rb'))

In [26]:
result = loaded_model.predict([[1234,345,4567,0,0]])

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [27]:
result

array([[43531.8304969]])